name: Deploy VitePress site to Pages

on:
    push:
        branches: [master]
        paths:
            - "docs/**"
            - "src/**"
    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: false

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source repo
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Build VitePress
              run: npm run docs:build

            - name: Deploy to waylis.github.io
              uses: peaceiris/actions-gh-pages@v4
              with:
                  personal_token: ${{ secrets.PERSONAL_TOKEN }}
                  publish_dir: docs/.vitepress/dist
                  external_repository: waylis/waylis.github.io
                  publish_branch: gh-pages
